name: "javascript algorithm"
run-name: "javascript algorithm"
on:
  push:
    branches:
      - main

jobs:
  test-bun-prject:
    runs-on: ubuntu-latest
    name: "Test algorithm with bun"
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: check version
        run: bun --version

      - name: Install dependencies
        run: bun i

      - name: Test the module
        run: bun test
